### ISSUE TITLE
IP options and fragment handling

### ISSUE THREAD

**Issue by mitalum** [Azure/DASH#9]
https://github.com/Azure/DASH/blob/6b2a638d6f620469fdff59716c65bb7286b5ef61/sirius-pipeline/sirius_parser.p4#L34

How should IP options and IP fragments be handled?

**Comment by KrisNey-MSFT** [comment]
We (in Azure) handle fragmentation w/VFP - @mitalum and @marian-pritsak (or really anyone) could you help us to add this to the behavioral model (if it isn't addressed)?  Some explanation below...

Fragments collect in a fragment cache. The 1st fragment should contain all of the headers needed.  We can send through to determine the action needed, and apply to the rest of the traffic.  If no action is taken in 3 seconds, we drop the fragment/fragment cache entry.  We follow industry standard handling of fragments (L3 devices handle them the same way/use the same logic).  

IP options are not used for decisions on rule or transformation to the packet.  We do not drop incoming packets because of IP options on outer header.

We do not drop packets if they have options or extensions on the outer header. We also do not add an option or extension when encapsulating a packet.

An incoming encapsulated IPv6 packet with extensions on outer header will not match rules with gre/vxlan conditions because next protocol in IPv6 header is the extension protocol and not the encap protocol.

**Comment by KrisNey-MSFT** [comment]
Closed in https://github.com/Azure/DASH/commit/a02a4d90b591d16b7354608b898aee94168f4ebc
